name: advanced-viz-cookbook
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - matplotlib
  - cartopy
  - metpy
  - geocat-viz
  - datashader
  - colorcet
  - holoviews
  - plotly
  - seaborn
  - bokeh
  - uxarray
  - pip:
      - sphinx-pythia-theme
