name: advanced-viz-cookbook
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pandas
  - matplotlib
  - cartopy
  - metpy
  - geocat-viz>=2023.10.0
  - colorcet
  - uxarray
  - datashader
  - geocat-datafiles
  - geoviews
  - tropycal
  - sphinx-pythia-theme
  - pip
  - pip:
      - jupyter_bokeh
