name: advanced-viz-cookbook
channels:
  - conda-forge
dependencies:
  - sphinx-pythia-theme
  - jupyter-book
  - jupyterlab
  - jupyter_bokeh
  - pandas
  - matplotlib
  - cartopy
  - metpy
  - geocat-viz>=2023.10.0
  - colorcet
  - hvplot
  - plotly
  - seaborn
  - uxarray
  - datashader
  - geocat-datafiles
  - geoviews
  - tropycal
