name: advanced-viz-cookbook
channels:
  - conda-forge
dependencies:
  - sphinx-pythia-theme
  - jupyter-book
  - jupyterlab
  - jupyterlab-myst
  - pandas
  - matplotlib
  - mystmd
  - nodejs
  - cartopy
  - metpy
  - geocat-viz>=2023.10.0
  - colorcet
  - cftime
  - xarray
  - geocat-datafiles
  - tropycal
  - netcdf4
