name: link-checker

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true

      - name: Install Jupyterbook
        run: mamba install -c conda-forge jupyter-book

      - name: Check for config file
        id: check_config
        uses: andstor/file-existence-action@v2
        with:
          files: "${{ inputs.path_to_notebooks }}/_config.yml"

      - name: Disable notebook execution
        if: steps.check_config.outputs.files_exists == 'true'
        shell: python
        run: |
          import yaml
          with open('${{ inputs.path_to_notebooks }}/_config.yml') as f:
            data = yaml.safe_load(f)
          data['execute']['execute_notebooks'] = 'off'
          with open('${{ inputs.path_to_notebooks }}/_config.yml', 'w') as f:
            yaml.dump(data, f)

      - name: Check external links
        run: |
          cd ${{ inputs.path_to_notebooks }}
          linkchecker --ignore-url "https://www.noaa.gov/jetstream" --ignore-url "https://weather.uwyo.edu/upperair/" --ignore-ssl-check ${{ inputs.build_command }}
