name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: build-book.yaml
    with:
      environment_name: advanced-viz-cookbook

  deploy:
    needs: build
    uses: deploy-book.yaml@main
