name: trigger-link-check
on:
  pull_request:

jobs:
  link-check:
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
    with:
      build_command: "jupyter-book build --builder linkcheck SPHINXOPTS=linkcheck_ignore=['https://weather.uwyo.edu/upperair/', 'https://www.noaa.gov/jetstream'] ."